export const techMap: { [key: string]: string } = {
  javascript: "devicon-javascript-plain",
  typescript: "devicon-typescript-plain",
  python: "devicon-python-plain",
  java: "devicon-java-plain",
  c: "devicon-c-plain",
  cplusplus: "devicon-cplusplus-plain",
  csharp: "devicon-csharp-plain",
  go: "devicon-go-plain",
  rust: "devicon-rust-plain",
  php: "devicon-php-plain",
  reactquery: "devicon-jquery-plain",

  html: "devicon-html5-plain",
  css: "devicon-css3-plain",
  react: "devicon-react-original",
  reactjs: "devicon-react-original",
  redux: "devicon-redux-original",
  vuejs: "devicon-vuejs-plain",
  angular: "devicon-angular-plain",
  nextjs: "devicon-nextjs-original",
  node: "devicon-nodejs-plain",
  next: "devicon-nextjs-original",
  nodejs: "devicon-nodejs-plain",
  expressjs: "devicon-express-original",
  django: "devicon-django-plain",
  flask: "devicon-flask-plain",
  laravel: "devicon-laravel-plain",
  ruby: "devicon-ruby-plain",
  rails: "devicon-rails-plain",
  symfony: "devicon-symfony-plain",

  docker: "devicon-docker-plain",
  kubernetes: "devicon-kubernetes-plain",
  git: "devicon-git-plain",
  github: "devicon-github-original",
  linux: "devicon-linux-plain",
  ubuntu: "devicon-ubuntu-plain",
  windows: "devicon-windows-plain",
  macos: "devicon-macos-plain",
  unix: "devicon-unix-plain",
  android: "devicon-android-plain",
  ios: "devicon-ios-plain",

  firebase: "devicon-firebase-plain",
  mongodb: "devicon-mongodb-plain",
  mysql: "devicon-mysql-plain",
  postgresql: "devicon-postgresql-plain",
  redis: "devicon-redis-plain",
};
